//ERRORS
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//FETCH PRODUCT LIST
export const FETCH_PRODUCTLIST_REQUEST = "FETCH_PRODUTLIST_REQUEST";
export const FETCH_PRODUCTLIST_SUCCESS = "FETCH_PRODUTLIST_SUCCESS";
export const FETCH_PRODUCTLIST_FAILURE = "FETCH_PRODUTLIST_FAILURE";